name: r3dgs
dependencies:
  - python=3.11.9
  - numpy=1.26.4
  - tqdm=4.66.4
  - pip=24.0
  - matplotlib=3.9.1
  - tensorboard=2.17.0
  - pip:
      - dearpygui==1.11.1
      - imageio==2.34.2
      - opencv-python==4.10.0.84
      - pillow==10.4.0
      - plyfile==1.0.3
      - scipy==1.14.0